config/routes.rb
Rails.application.routes.draw do

  root 'images#index'
  get 'upload', to: 'images#new', as: 'upload'
  resources :images
  resources :categories, except: [:index]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :main_image
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :category
  has_one_attached :main_image

  validate :acceptable_image

  before_save :update_image_attributes

  def acceptable_image
    unless main_image.attached?
      unless main_image.byte_size <= 1.megabyte
        errors.add(:main_image, "is too big")
      end
    end
    acceptable_types = ["image/jpeg", "image/png"]
    unless acceptable_types.include?(main_image.content_type)
      errors.add(:main_image, "must be a JPEG or PNG")
    end
  end

  private

  def update_image_attributes
    if main_image.present? && main_image.changed?
      self.image_content_type = main_image.content_type
      self.image_file_size = main_image.byte_size
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :getCategoryNav

  private
  def getCategoryNav
    @categoryNav = Category.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :set_images, only: [:show, :edit, :update, :destroy]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "Category Created"
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "Category Updated"
      redirect_to category_path
    else
      render 'edit'
    end
  end

  def destroy
  end

  private
  def set_category
    @category = Category.find_by id: params[:id]
  end

  def set_images
    @images = Image.where(category_id: params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:edit, :update, :destroy]

  def index
    @images = Image.all
    @active = 'active'
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)

    if @image.save
      flash[:notice] = "Image saved"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @image.update(image_params)
      flash[:notice] = "Image Updated"
      redirect_to category_path(@image.category_id)
    else
      render 'edit'
    end
  end

  def destroy
    category_id = @image.category_id
    @image.main_image.purge
    @image.destroy
    flash[:notice] = "Image Deleted"
    redirect_to category_path(category_id)
  end

  private

  def set_image
    @image = Image.find_by id: params[:id]
  end

  def image_params
    params.require(:image).permit(:image, :category_id, :image_title, :image_description, :image_file_size, :image_content_type, :remote_image_url, :main_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <!--Check for errors-->
  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <!--Show errors-->
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'col-form-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <br>
  <%= f.submit 'Submit', class:'btn btn-primary' %>
  <%= link_to 'Cancel', root_path, class: 'btn btn-default' %>
<% end %>

app/views/categories/edit.html.erb
<h2>Edit Category</h2>
<div class="container">
  <%= render 'form', category: @category %>
</div>

<% if @images.present? %>
  <div class="container-fluid">
    <h2 class="mt-5">Images in <%= @category.name %></h2>
    <div class="row">
      <% @images.each do |image| %>
        <div class="col-md-2 col-sm-4 edit-category">
          <div class="photo photo-type-line">
            <div class="edit-photo-img">
              <%= image_tag rails_blob_path(image.main_image), class: 'img-fluid' %>
            </div>
          </div>
          <div class="buttons">
            <%= link_to 'Edit', edit_image_path(image), class: 'btn btn-warning' %>
            <%= link_to 'Delete', image_path(image), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/categories/new.html.erb
<h2>Add New Category</h2>
<div class="container">
  <%= render 'form', category: @category %>
</div>

app/views/categories/show.html.erb
<div id="gallery">
  <div class="category-title">
    <h2><%= @category.name %></h2>
    <small class="float-right"><%= link_to "Edit", edit_category_path(@category) %></small>
  </div>
  <div class="container-fluid">
    <% if @images.present? %>
      <div class="row">
        <% @images.each do |image| %>
          <div class="col-md-3 col-sm-6 imagebg" style="background: url('<%= rails_blob_path(image.main_image) %>'); background-size: cover;">
            <div class="photo photo-type-line">
              <a href="<%= rails_blob_path(image.main_image) %>" class="photo-hover image-fluid" data-lightbox="my-images" data-title="<%= image.image_title %>">
                <div class="photo-info">
                  <div class="headline"><%= image.image_title %></div>
                  <div class="line"></div>
                  <div class="description">
                    <%= image.image_description %>
                  </div>
                </div>
                <div class="mask"></div>
              </a>

            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/images/_form.html.erb
<%= form_for @image, html: {multipart: true} do |f| %>
  <!--Check for errors-->
  <% if @image.errors.any? %>
    <% @image.errors.full_messages.each do |msg| %>
      <!--Show errors-->
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :image_title, class: 'col-form-label' %>
    <%= f.text_field :image_title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :category, class: 'col-form-label' %>
    <%= f.select :category_id, Category.all.map {|x| [x.name, x.id]}, {include_blank: 'Select One'}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image_description, class: 'col-form-label' %>
    <%= f.text_field :image_description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :main_image, class: 'col-form-label' %>
    <%= f.file_field :main_image, class: 'form-control' %>
  </div>

  <!--<div class="form-group">
      <%#= f.label :remote_image_url, 'or image url', class: 'col-form-label' %>
  <%#= f.text_field :remote_image_url, class: 'form-control' %>
    </div>-->
  <br>
  <%= f.submit 'Submit', class:'btn btn-primary' %>
  <%= link_to 'Cancel', root_path, class: 'btn btn-default' %>
<% end %>

app/views/images/edit.html.erb
<h2>Edit Image</h2>

<div class="container">
  <%= render 'form', image: @image %>
</div>

app/views/images/index.html.erb
<div id="gallery">
  <h2>All Images</h2>
  <div class="container-fluid">
    <% if @images %>
      <div class="row">
        <% @images.each do |image| %>
          <div class="col-md-3 col-sm-6 imagebg" style="background: url('<%= rails_blob_path(image.main_image) %>'); background-size: cover;">
            <div class="photo photo-type-line">
              <a href="<%= rails_blob_path(image.main_image) %>"
                 class="photo-hover image-fluid"
                 data-lightbox="my-images"
                 data-title="<%= image.image_title %>">
                <div class="photo-info">
                  <div class="headline"><%= image.image_title %></div>
                  <div class="line"></div>
                  <div class="description">
                    <%= image.image_description %>
                  </div>
                </div>
                <div class="mask"></div>
              </a>

            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/images/new.html.erb
<h2>Upload Image</h2>

<div class="container">
  <%= render 'form', image: @image %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RGallery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark p-0">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to 'Home', root_path, class: "nav-link #{@active}" %>
            </li>
            <% @categoryNav.each do |category| %>
              <li class="nav-item">
                <%= link_to category.name, category_path(category), class: "nav-link #{'active' if category.id == params[:id].to_i}" %>
              </li>
            <% end %>
          </ul>
          <ul class="navbar-nav nav2">
            <li class="nav-item">
              <%= link_to 'Upload Photo', upload_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Add Category', new_category_path, class: 'nav-link' %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <section class="mt-5">
      <div class="container-fluid">
        <!--Alert & Messages-->
        <% if flash[:notice] %>
          <div class="alert alert-success"><%= flash[:notice] %></div>
        <% end %>
        <% if flash[:alert] %>
          <div class="alert alert-danger"><%= flash[:alert] %></div>
        <% end %>

        <%= yield %>
      </div>
    </section>


    <footer>
      <div class="container">
        <p class="text-center">Copyright &copy; 2022, rGallery</p>
      </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    <script src="<%= asset_path('/js/lightbox.js') %>"></script>
  </body>
</html>